driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: ubuntu-14.04
    run_list:
        - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[wrapper-nginx::default]

